#WASHINGTON'S REFERENCE DATE ASK FOR THE DAY BEFORE THE GAME, AND THE MERGED 'REFERENCE' DATE PULLS STANDINGS AND TEAM PERFORMANCE AT CONCULSION OF THAT DAY
#WE ASK FOR DAY BEFORE ON WASHINGTON MERGEID SO THAT WE SEE WHAT STANDINGS ARE DAY BEFORE GAME
MERGED$OPP.REF.DATE.MERGEID <- paste(MERGED$TEAM, MERGED$"GAME DATE", sep="-")


AWAY.MERGE.ID <-MERGED[c(8,2,3,5,4)]
names(AWAY.MERGE.ID)[2] <- "OPP-W"
names(AWAY.MERGE.ID)[3] <- "OPP-L"
names(AWAY.MERGE.ID)[4] <- "OPP-GB"
names(AWAY.MERGE.ID)[5] <- "OPP-W/L %"


WSN.FINAL.1 <- merge(WSN, AWAY.MERGE.ID,by="OPP.REF.DATE.MERGEID")
WSN.FINAL.1 <-WSN.FINAL.1[c(3,2,1,4,5,6,7,8)]

#========================
#USE OPP.REF.DATE.MERGEID EVEN THOUGH WE ARE LOOKING TO FIND OUR (HOME TEAM), SINCE FILE INCLUDES OUR OWN TEAM
#WSN<- MERGED[ which(MERGED$TEAM=='WSN'), ]

HOME.MERGE.ID <- AWAY.MERGE.ID
names(HOME.MERGE.ID)[1] <- "HOME.REF.DATE.MERGEID"
names(HOME.MERGE.ID)[2] <- "HOME-W"
names(HOME.MERGE.ID)[3] <- "HOME-L"
names(HOME.MERGE.ID)[4] <- "HOME-GB"
names(HOME.MERGE.ID)[5] <- "HOME-W/L %"

WSN.FINAL.1$"GAME DATE"<-as.Date(WSN.FINAL.1$"GAME DATE")
WSN.FINAL.1$REF.DATE <-WSN.FINAL.1$"GAME DATE" -1
WSN.FINAL.1$HOME.REF.DATE.MERGEID <- paste(WSN.FINAL.1$TEAM, WSN.FINAL.1$REF.DATE, sep="-")

#====================================

WSN.FINAL <- merge(WSN.FINAL.1, HOME.MERGE.ID,by="HOME.REF.DATE.MERGEID")
WSN.FINAL <- WSN.FINAL[order(WSN.FINAL$"GAME DATE"),]
rownames(WSN.FINAL) <-NULL
rm(WSN.FINAL.1)

#=================================================================
WSN.FINAL <-WSN.FINAL[c(3,10,2,1,5,4,6,7,8,9,11,12,13,14)]

setwd("C:/Users/Garrett/Google Drive/Career/Companies/Accepted Companies/Washington Nationals/Work/Standings")

write.csv(WSN.FINAL, "NATS.MASTER_FILE.csv", row.names=FALSE)
####COMPLETE